In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [4]:
((2 * np.ones(20)) ** np.arange(1, 21)) / np.arange(1, 21)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [6]:
np.array((0.1 * np.ones(6)) ** (3 * np.arange(0, 6)) * (0.2 * np.ones(6)) ** (4 * np.arange(0, 6))).sum()

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [34]:
m = np.zeros(8**2).reshape(8,8)
m[::2 , ::2] = 1
m[1::2 , 1::2] = 1
m

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [40]:
X = np.random.random((5, 2))
print(X)
r = np.sqrt(X[:, 0] ** 2 + X[:, 1] ** 2)
u =  np.arctan2(X[:, 1], X[:, 0])
X = np.array([r,u]).T
X

[[0.66371284 0.13213681]
 [0.76672992 0.2762579 ]
 [0.23947234 0.83168734]
 [0.35106265 0.4383145 ]
 [0.392206   0.41499795]]


array([[0.67673841, 0.19651783],
       [0.81498049, 0.34582703],
       [0.86547723, 1.29044427],
       [0.56157331, 0.89548382],
       [0.57100687, 0.81362635]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [115]:
X = np.random.random((10, 10))

idx = np.unravel_index(np.argmax(X), X.shape)
idx

(2, 2)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [119]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

print(X)
print(y)

dist = np.sqrt((X[:,0]-y[:,0])**2+(X[:,1]-y[:,1])**2)
X[np.argmin(dist), :]

[[0.52061083 0.21025361]
 [0.4570747  0.23982993]
 [0.3089978  0.21341115]
 [0.56095657 0.31471973]
 [0.75703678 0.71244906]
 [0.64989751 0.05365037]
 [0.52284682 0.80220251]
 [0.32714994 0.47206228]
 [0.38623735 0.97536965]
 [0.78639407 0.98410636]]
[[0.88160947 0.53815742]]


array([0.75703678, 0.71244906])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [126]:
x = np.linspace(-3,3, 10)

x[x < 0] = x[x < 0] ** 2 + 2 * x[x < 0] + 6
x[(0 <= x) & (x <= 2)] = x[(0 <= x) & (x <= 2)] + 6
x[x >= 2] = x[x >= 2] ** 2 + 4 * x[x >= 2] + 6
x

array([123.        ,  79.04938272,  57.41975309,  51.        ,
        57.41975309,  71.44444444,  83.        ,  95.44444444,
        20.77777778,  27.        ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [145]:
X = np.random.random((10, 10))


X = X.T - X.mean(1)
X = X.T

X.mean(1)

array([-2.22044605e-17,  2.22044605e-17, -2.22044605e-17, -1.11022302e-16,
        6.66133815e-17,  0.00000000e+00, -2.22044605e-17, -9.99200722e-17,
       -2.22044605e-17,  0.00000000e+00])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [177]:
X = np.random.normal(loc=5, scale=2., size=1000)

loc = X.sum() / X.size
scale = ((X - loc) ** 2).sum() / X.size
loc, scale**0.5

(4.974682690842866, 2.0366683234584744)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [180]:
a = np.ones((5, 5)) * np.arange(5)
a += a.T
a %= 5
a

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [183]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 10)    

[0, 0, 0, 0, 0, 0, 4, 3, 4, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [197]:
def foo(x, c):
    s = np.sum(x)
    
    sums = np.repeat(np.cumsum(x), c).reshape((len(x), c)).astype("float32")
    val = s * np.random.random(c)
    
    sums -= val.T
    sums[sums >= 0] = 0
    
    return sums.argmax(0)

foo([50, 3, 1, 7, 20], 10)    

array([0, 0, 0, 4, 4, 0, 0, 0, 4, 4], dtype=int32)